version: '2'

services:
  mongodb:
    image : mongo
    container_name: mongo
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    volumes:
      - 'mongo_data:/data/db'

volumes:
  mongo_data:
    driver: local